### ISSUE TITLE
Compiling files with the .ts extension

### ISSUE THREAD

**Issue by lpil** [pb82/typescript-support-brunch#1]
Hello!

I've trying out this plugin, and I'm confused as to how to make it work with files with the `.ts` extension, for example, `main.ts`. Brunch doesn't seem to pick up these files.

I can resolve this issue by using the `.js` extension, but then my editor incorrectly detects these files as Javascript, resulting in it reporting errors.

Is it possible to use the `.ts` extension?

**Comment by pb82** [comment]
Hi,

yes that should work. I created a minimal example:

https://github.com/pb82/brunch-typescript-simple

```
> brunch build
> info: compiled test.ts into app.js in 987ms
```

Could you please verify if that one works for you?
However there was a bug when no Typescript config was given in `brunch-config.coffee`. I fixed that one with 0.0.3.

**Comment by lpil** [comment]
Hello!

Shortly afterwards it started working, and I'm unclear as to what changed. Oh well!

Can you confirm whether the ES6 module import and export syntax work with this? I've been having trouble with that too.

**Comment by pb82** [comment]
Yes module support also works. If you are only using internal modules then you don't need any settings just reference your files with `reference path`. If you want to use typescript with something like require.js, then you need to enable it with:

``` coffeescript
plugins:
  Typescript:
    tscArgs: "--module commonjs"
```

Then typescript will compile reqiure statements like `import X = require('X');` and use the underlying module loader.

**Comment by lpil** [comment]
And the official javascript module syntax should work?

``` javascript
import foo from 'bar';

export default { one, two };

```
